### ISSUE TITLE
Some extra unicode blocks to look at

### ISSUE THREAD

**Issue by joshka** [thomas-mauran/chess-tui#1]
Hey, this is a cool idea :)

I just wanted to point you to some unicode blocks that I've found that could be useful in making cool looking chess symbols:
- https://en.wikipedia.org/wiki/Block_Elements
- https://en.wikipedia.org/wiki/Geometric_Shapes_(Unicode_block)
- https://en.wikipedia.org/wiki/Symbols_for_Legacy_Computing

**Comment by thomas-mauran** [comment]
Thank you very much ! I am going to rework the piece style using those soon 👍.
If you want to submit a piece design feel free to do a quick PR !
