### ISSUE TITLE
Add Nix OS/package-manger installation to readme

### ISSUE THREAD

**Issue by shuvashish76** [thomas-mauran/chess-tui#100]
Thanks to @ByteSudoer @r-ryantm  chess-tui already [available on Nix](https://search.nixos.org/packages?channel=24.05&show=chess-tui&from=0&size=50&sort=relevance&type=packages&query=chess-tui+) _([Commits History](https://github.com/NixOS/nixpkgs/commits/nixos-24.05/pkgs/by-name/ch/chess-tui/package.nix))_

Nix is an universal package-manager and can be installed on any operating system.
Add instructions for the users about how to install for NixOS _(linux distributionn)_ or via Nix package-manager _(any OS)_
BTW it should also work on android on [Termux](https://f-droid.org/en/packages/com.termux/) or [Nix-on-Droid](https://f-droid.org/en/packages/com.termux.nix/) via nix package-manager. I've tried other TUI packages before but not yet chess-tui.

**Comment by thomas-mauran** [comment]
Nice I didn't know that. Do you want to make the pr for that issue ? Else I will do it

**Comment by shuvashish76** [comment]
Actually it doesn't look good on Readme page. IMO all the documentation, installation instructions etc should be moved to GitHub's Wiki page _(maybe to a dedicated website in future)_. Simple markdown based, GitHub hosted site should be good enough with the help of https://github.com/squidfunk/mkdocs-material. What do you think?

Instead of all installation instructions on Readme page show this image/hyperlink : https://repology.org/project/chess-tui/badges _[(idea from Calibre](https://github.com/kovidgoyal/calibre#calibre-package-versions-in-various-repositories))_

**Comment by thomas-mauran** [comment]
> Actually it doesn't look good on Readme page. IMO all the documentation #94, installation instructions, changelogs, project specific news/blogs? etc should be moved to GitHub's Wiki page _(maybe to a dedicated website in future)_. Simple markdown based, GitHub hosted site should be good enough with the help of https://github.com/squidfunk/mkdocs-material. What do you think?

Great idea, as you saw it in #94 it is planned to document chess tui as part of a big refactor of the code I am starting. Improving the readability and spliting in more files. Putting the installation instructions here could be great.

> 
> Instead of all installation instructions on Readme page show this image/hyperlink : https://repology.org/project/chess-tui/badges _[(idea from Calibre](https://github.com/kovidgoyal/calibre#calibre-package-versions-in-various-repositories))_
> 
Perfect, I was wondering how we could still have a good way for users to quickly see if they can install the project with their package manager. This solves it

**Comment by shuvashish76** [comment]
https://thomas-mauran.github.io/chess-tui/docs/Installation/NixOS
Closing...thankyou :)

**Comment by thomas-mauran** [comment]
True gonna be improving that thanks @shuvashish76 !
