### ISSUE TITLE
"En Passant" Move Not Functioning Correctly

### ISSUE THREAD

**Issue by DNEGEL3125** [thomas-mauran/chess-tui#108]
## Description

While playing a game in the Normal game mode, I attempted to perform an "en passant" move with a black pawn to capture a white pawn that had moved forward two squares in the previous turn. Although the black pawn moved to the correct position, the white pawn did not disappear from the board as it should have according to the rules of chess.

## To Reproduce

1. Clone the repository using `git clone https://github.com/thomas-mauran/chess-tui.git`
2. Run the project using `cargo run`.
3. Select the Normal game mode from the main menu.
4. Play the following moves:
    1. ♟ e2-e4     ♙ e2-e4
    2. ♚ e1-e2     ♙ e4-d5
    3. ♟ f2-f4     ♙ d5-c6

## Expected behavior

The white pawn should be removed from the board when the black pawn moves to its capture position during the "en passant" move.

## Screenshots

<img width="1157" alt="截屏2024-11-21 17 05 31" src="https://github.com/user-attachments/assets/cc5573e1-a4a9-4609-bc88-2445e8c766ff">

## Environment

- OS: MacOS
- Terminal Emulator: kitty
- Font: Hack Nerd Font
- Crate version: 1.4.0

**Comment by thomas-mauran** [comment]
Nice catch, fixing that tonight
