### ISSUE TITLE
Players can move the opponent's pawns

### ISSUE THREAD

**Issue by skythub** [thomas-mauran/chess-tui#116]
## Description
In the chess-tui game, players can move the opponent's pawns, which violates the rules of chess. This issue disrupts the gameplay by allowing unintended moves that break the turn-based logic.

## To Reproduce
- Start a game in chess-tui.
- Attempt to move a pawn belonging to the opponent.
- Observe that the move is allowed, even though it should not be.

## Expected behavior
Players should only be able to move pieces of their own color and only on their turn. The game should restrict pawn movement to adhere to the rules of chess.

## Screenshots
If applicable, add screenshots, gifs or videos to help explain your problem.

## Environment
- OS: Linux
- Terminal Emulator: Gnome Console 
- Font: MesloLGS
- Crate version: 1.5.0

## Additional context
To resolve this issue, the game logic should validate the turn and restrict movement to pieces belonging to the active player. This would ensure the integrity of the gameplay and adherence to chess rules.

> PS: I stumbled across this project by chance and I like the idea, great initiative and several ideas to propose. I will surely contribute in my spare time.

**Comment by thomas-mauran** [comment]
Hello @skythub thanks for your issue, I didn't managed to reproduce the bug in a normal game or against a bot, when starting as white I can't select the black pieces to make them move, do you have any screenshot so I can try to reproduce ?

**Comment by thomas-mauran** [comment]
Ok @skythub I managed to reproduce the bug and am fixing it as part of the multiplayer pr

**Comment by thomas-mauran** [comment]
This is in theory solved in the pr #119
