### ISSUE TITLE
Mouse support? Is it technically possible?

### ISSUE THREAD

**Issue by franzmondlichtmann** [thomas-mauran/chess-tui#57]
## Feature Request

A question: Mouse support? Is it technically possible?

**Comment by joshka** [comment]
Yes - Crossterm supports click events. You'd need to map these to the screen location of the board positions however.

**Comment by thomas-mauran** [comment]
That could be very nice do you want to make a pr @franzmondlichtmann ?

**Comment by franzmondlichtmann** [comment]
Oh sorry, I was just curious, I don't actually know how to implement that. :)

**Comment by thomas-mauran** [comment]
No problem thanks for the issue it's a great idea

**Comment by pSnehanshu** [comment]
This sounds interesting to me. I will jump into it when I can.

**Comment by thomas-mauran** [comment]
> This sounds interesting to me. I will jump into it when I can.

that could be very nice mate looking forward to it !

**Comment by thomas-mauran** [comment]
This is being done by @theonlytruealex in the #85 pr
