### ISSUE TITLE
Ascii mode

### ISSUE THREAD

**Issue by franzmondlichtmann** [thomas-mauran/chess-tui#58]
## Problem

Old school ascii mode, just like in gnuchess. The player has uppercase letters and the enemy has lowercase letters.
p = pawn, k = king, q = queen, b = bishop, r = rook, n = knight

![image](https://github.com/thomas-mauran/chess-tui/assets/105480088/9845dd05-098a-424e-858a-afb11226c200)

**Comment by thomas-mauran** [comment]
This is a good idea and could be implemented easily.
Maybe we could have another clap cli argument like --ascii to run chess-tui in ascii mode and replace every piece by it's character, we also will need to see how it renders on the board making sure it is not too small

**Comment by pSnehanshu** [comment]
Fyi, I am working on this, and I will create a PR soon.

https://github.com/pSnehanshu/chess-tui/tree/feat/ascii-mode

**Comment by pSnehanshu** [comment]
Here you go #60
