### ISSUE TITLE
3 fold repetition

### ISSUE THREAD

**Issue by nicholasmello** [thomas-mauran/chess-tui#67]
## Description
3 fold repetition only checks moves in a row, it should check if the position repeats regardless of order

## To Reproduce
Play a game and repeat the position, outside of the same order

## Expected behavior
Draw in all repetition scenarios

## Environment
OS: Linux (NixOS)
Terminal Emulator: Alacritty

## Additional context
This function just needs to be rewritten
```rust
    pub fn draw_by_repetition(&self) -> bool {
        if self.move_history.len() >= 9 {
            let last_ten: Vec<PieceMove> =
                self.move_history.iter().rev().take(9).cloned().collect();

            if (last_ten[0].clone(), last_ten[1].clone())
                == (last_ten[4].clone(), last_ten[5].clone())
                && last_ten[4].clone() == last_ten[8].clone()
                && (last_ten[2].clone(), last_ten[3].clone())
                    == (last_ten[6].clone(), last_ten[7].clone())
            {
                return true;
            }
        }
        false
    }
```

**Comment by thomas-mauran** [comment]
Oh yes you are right ! I always thought 3 fold rep needed to be consecutive, do you want to take the pr ? else I might fix it this week, nice catch @nicholasmello

**Comment by nicholasmello** [comment]
I'll take a look at it if I have time, my focus is on getting #65 flushed out. If someone takes a look at this before me, one thing to remember is ["Two positions are by definition "the same" if the same types of pieces occupy the same squares, the same player has the move, the remaining castling rights are the same and the possibility to capture en passant is the same"](https://en.wikipedia.org/wiki/Threefold_repetition). Castling rights and the possibility of en passant are the obscure rules that often get left out.
