### ISSUE TITLE
Wrong path for chess-tui config file

### ISSUE THREAD

**Issue by damien-mathieu1** [thomas-mauran/chess-tui#70]
## Description
For now the chess-tui config file in which there is the engine path for the bot is created directly at the root of the home directory. **(~/.chess-tui)**

## To Reproduce
Run chess-tui with **-e** option for the engine path and the configuration file will be created.

## Expected behavior
The configuration file should be located in a chess-tui directory in the .config directory as follow : **~/.config/chess-tui/config.toml**
Also, it would be better if the configuration file is created whether or not there is an option on launch of chess-tui.

## Environment

- OS: Arch Linux
- Terminal Emulator: Fish

**Comment by damien-mathieu1** [comment]
Hello ! 

I would like to take this issue if possible ! :smile:

**Comment by thomas-mauran** [comment]
good idea in the new toml file we could have the following fields: 

```toml
engine_path = <path>
display_mode = <display_mode_from_enum>
```

make sure to change the way those 2 variables are implemented

**Comment by damien-mathieu1** [comment]
Will do !
