### ISSUE TITLE
Enable Link-Time Optimization (LTO)

### ISSUE THREAD

**Issue by zamazan4ik** [thomas-mauran/chess-tui#79]
Hi!

I noticed that in the `Cargo.toml` file Link-Time Optimization (LTO) for the project is not enabled. I suggest switching it on since it will reduce the binary size (always a good thing to have) and will likely improve the application's performance a bit.

I suggest enabling LTO only for the Release builds so as not to sacrifice the developers' experience while working on the project since LTO consumes an additional amount of time to finish the compilation routine. If you think that a regular Release build should not be affected by such a change as well, then I suggest adding an additional `dist` or `release-lto` profile where additionally to regular `release` optimizations LTO will also be added. Such a change simplifies life for maintainers and others interested in the project persons who want to build the most performant version of the application. Using ThinLTO should also help to reduce the build-time overhead with LTO. If we enable it on the Cargo profile level, users, who install the application with `cargo install`, will get the LTO-optimized version "automatically". E.g., check `cargo-outdated` Release [profile](https://github.com/kbknapp/cargo-outdated/blob/master/Cargo.toml#L48).

Basically, it can be enabled with the following lines:

```
[profile.release]
lto = true
```

Thank you.

P.S. It's more like an improvement idea rather than a bug. I created the issue just because the Discussions are disabled for the repo for now.

**Comment by thomas-mauran** [comment]
I didn't know about that I will look into it ! Maybe you want to make the pr to implement it ?

**Comment by zamazan4ik** [comment]
Here we go: https://github.com/thomas-mauran/chess-tui/pull/80

**Comment by mfernd** [comment]
@zamazan4ik If we want to optimize further, we could add all the size optimization:

```toml
[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
strip = true
```
(From: [github.com/johnthagen/min-sized-rust](https://github.com/johnthagen/min-sized-rust))

With this we would have a binary size of 1,1Mo instead of 2Mo (and 1.7Mo with just the LTO optimization)

Also, I checked the compilation time and it doesn't change. And I don't think it impacts the running speed of the game, considering the scope of the project.

**Comment by zamazan4ik** [comment]
> If we want to optimize further, we could add all the size optimization:

Sure. I've updated the PR.

> With this we would have a binary size of 1,1Mo instead of 2Mo (and 1.7Mo with just the LTO optimization)

Great!

> Also, I checked the compilation time and it doesn't change. And I don't think it impacts the running speed of the game, considering the scope of the project.

Yep, I expected such things. At least the binary size is optimized which is also a good thing to achieve.

**Comment by thomas-mauran** [comment]
perfect thanks for the contributions @zamazan4ik @mfernd
